# Reference: https://github.com/3scale/apicast-operator/blob/3scale-2.12.0-GA/doc/apicast-crd-reference.md
apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: apim-demo-tls-production
spec:
  # Controls on which port APIcast should start listening for HTTPS connections.
  httpsPort: 8443
  # References secret containing the X.509 certificate in the PEM format and the X.509 certificate secret key
  httpsCertificateSecretRef:
    name: apim-demo-production-tls-secret
  # The local timezone of the APIcast deployment pods. Its value must be a compatible value with the tz database
  timezone: Europe/Paris
  replicas: 3
  adminPortalCredentialsRef:
    name: apim-demo-tls-production-3scaleportal-secret
  deploymentEnvironment: production
  configurationLoadMode: boot
  # Log level for the OpenResty logs
  # Possible values: debug | info | notice | warn | error | crit | alert | emerg
  logLevel: info
  # OpenTracing configuration
  openTracing:
    # Controls whether OpenTracing integration with APIcast is enabled - default: false
    enabled: true
    # Controls which OpenTracing library is loaded. At the moment the supported values are: jaeger. 
    # If not set, jaeger will be used
    tracingLibrary: jaeger
    # Secret reference with the tracing library-specific configuration. 
    # Each supported tracing library provides a default configuration file which is used if tracingConfigSecretRef 
    # is not specified
    tracingConfigSecretRef: 
      name: selfmanaged-tls-production-jaeger-secret
  # Allows to set the log level for the logs related to OpenID Connect integration 
  # Possible values: debug | info | notice | warn | error | crit | alert | emerg
  oidcLogLevel: error
  pathRoutingEnabled: false
  responseCodesIncluded: true
  cacheConfigurationSeconds: 300
  managementAPIScope: status
  # Controls the OpenSSL Peer Verification
  # Possible values: 
  # - false (default): disable peer verification
  # - true: enable peer verification
  openSSLPeerVerificationEnabled: false
  # Enables additional information on Prometheus metrics; 
  # some labels will be used with specific information that will provide more in-depth details about APIcast.
  # The metrics that will have extended information are:
  # - total_response_time_seconds: labels service_id and service_system_name
  # - upstream_response_time_seconds: labels service_id and service_system_name
  # - upstream_status: labels service_id and service_system_name
  extendedMetrics: true
  # The values below reflect the defaults for managed production APICast
  resources:
    requests:
      memory: 64Mi
      cpu: 500m
    limits:
      memory: 128Mi
      cpu: 1000m